blank_issues_enabled: false
contact_links:
  - name: Wiki
    about: Useful information about the mod
    url: https://modrepo.de/minecraft/car/wiki
  - name: FAQ
    about: Frequently asked questions
    url: https://modrepo.de/minecraft/car/faq
